### ISSUE TITLE
Toolkit main page: spacing

### ISSUE THREAD

**Issue by dutch-embree** [freepress/internet2016#38]
spacing is off on this page - in general content is weighted to the right

specifically: 
resources icon should line up better w/ text - move it up

**Comment by drewrwilson** [comment]
Two tasks here:
- [x] center the grid
- [x] adjust images/css to make them better line up with the text

1st one is straight fwd.

The 2nd one is a little tricky to do with code because the images are all a little different. ie two of them have lots of whitespacing at the tops of the images whereas others are trimmed. 

![image](https://cloud.githubusercontent.com/assets/4324656/9791067/4a1b4920-57a7-11e5-9bb0-380d584c37c7.png)

I think we need to adjust the images as a first step to make them all consistent. @dutch-embree could  you adjust the images? I think it would involve moving the image part up and having the white space below it. And I'll do the grid centering piece in the mean time

**Comment by dutch-embree** [comment]
updated images: 
https://github.com/freepress/internet2016/blob/new-styles/assets/img/icons/toolkit-icon-resources3.png
https://github.com/freepress/internet2016/blob/new-styles/assets/img/icons/toolkit-icons-Team-Up3.png

**Comment by drewrwilson** [comment]
Looking good! 

![image](https://cloud.githubusercontent.com/assets/4324656/9793267/a0e8ed60-57b2-11e5-878f-112ea019a844.png)
